OPEN MASTER KEY DECRYPTION BY PASSWORD = 'key';
OPEN SYMMETRIC KEY UserKey DECRYPTION BY CERTIFICATE Usercert;
UPDATE transactions.intiqal
SET intiqal_no = EncryptByKey(Key_GUID('UserKey'), CONVERT(NVARCHAR(50), '473'))
WHERE intiqal_id = '83255baf-3e80-4a86-917e-e7dbcc5b5a94';
CLOSE SYMMETRIC KEY UserKey;
CLOSE MASTER KEY;